### ISSUE TITLE
Question about the pixel-level CLIP features.

### ISSUE THREAD

**Issue by Chuan-10** [ywyue/FiT3D#12]
Hi, thank you for the excellent work—it’s truly inspiring!

I have a question regarding the computation of pixel-level CLIP features. Could you please clarify how these features are obtained, both before and after fine-tuning? Additionally, are these features represented in the CLIP feature space?

Thank you in advance for your time and insights!

**Comment by ywyue** [comment]
Hi @Chuan-10, thank you for your interest and kind words.

> Could you please clarify how these features are obtained, both before and after fine-tuning?

Those features are from the last layer of the frozen vision transformer. See [here](https://github.com/ywyue/FiT3D/blob/1d7c5327a5192022d76a41acf438d83a9aeb380a/app.py#L257) in the demo and our [notebook](https://colab.research.google.com/github/ywyue/FiT3D/blob/main/FiT3D_demo.ipynb). 

For models before finetuning, we load the weights from timm: https://huggingface.co/timm/vit_base_patch16_clip_384.laion2b_ft_in12k_in1k

For models after finetuning, we load the weights of our finetuned model.

Please note those features are not pixel-level, instead they are patch-level. The resolution of the features is downscaled by 16 compared with the original image due to the patch size of 16.

> Additionally, are these features represented in the CLIP feature space?

I am not sure whether I understand this question correctly. To compute similarity between a text query and image features, you  need a text encoder. For the original model, I am not aware of where is the pretrained text encoder for the pretrained timm model. For the finetuned model, we also don't have aligned a text encoder because we only finetune image features. I am not sure whether I answered your question.

Feel free to let me know if there is further concern.

**Comment by Chuan-10** [comment]
Got it, thanks for the quick and detailed explanation! That clears up my questions. Appreciate it!
