### ISSUE TITLE
Preprocessing Scannetpp

### ISSUE THREAD

**Issue by Glanceyes** [ywyue/FiT3D#4]
Thank you for sharing your excellent work.

I have a question regarding the preprocessing of the ScanNetPP dataset, as mentioned in the [README](https://github.com/ywyue/FiT3D/tree/main/scannetpp_preprocess).

When I run the following command: `python reorganize_data.py --data_root=../scannetpp_data`

I encounter the following error: 
`FileNotFoundError: [Errno 2] No such file or directory: ../scannetpp_data/data/beb802368c/dslr/undistorted_images`

![Image 2024-10-07 오전 11 28 38](https://github.com/user-attachments/assets/18436bff-6a89-4d36-8be4-f16e39f4df88)

I redownloaded the ScanNetPP dataset, thinking that it might not have been fully downloaded, but the error persists. 
Could you please advise on how to resolve this issue?

Thanks.

**Comment by ywyue** [comment]
Hi @Glanceyes , thanks for your interest in our work and for pointing out this issue!

Previously, I cleaned and reorganized the code, which caused this issue. As shown in your screenshot, there are no `undistorted_images` for scene `beb802368c` because it is a test scene and we have only downscaled and undistorted scenes in `nvs_sem_train.txt` and `nvs_sem_val.txt` (i.e. train and val scenes, in total 280).

Now I have added a commit to fix this and it should work now. Please retry and feel free to let me know if the issue still exists.

P.S. Because you already ran `reorganize_data.py` and moved 6 scenes (shown in your screenshoot), when rerunning `reorganize_data.py`, please skip those 6 scenes, otherwise it will lead to FileNotFoundError again.
